import { Flex, StyledLink } from '@music-room/ui';
import Head from 'next/head';
import { PropsWithChildren, ReactElement, ReactNode } from 'react';
import * as Styles from './Layout.styles';

type Props = {
  appTitle?: string;
  header?: ReactNode;
};

export const Layout = ({
  children,
  header,
  appTitle = 'Create Next App',
}: PropsWithChildren<Props>): ReactElement => (
  <Styles.Page>
    <Head>
      <title>{appTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header>{header}</header>

    <Styles.Main>{children}</Styles.Main>

    <footer>
      <Flex justifyContent="center">
        <StyledLink
          href="https://github.com/wmalarski"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by @me
        </StyledLink>
      </Flex>
    </footer>
  </Styles.Page>
);
