import { Flex } from '@music-room/ui';
import Head from 'next/head';
import { PropsWithChildren, ReactElement, ReactNode } from 'react';

type Props = {
  appTitle?: string;
  header?: ReactNode;
};

export const Layout = ({
  children,
  header,
  appTitle = 'Create Next App',
}: PropsWithChildren<Props>): ReactElement => (
  <div>
    <Head>
      <title>{appTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header>{header}</header>

    <main>{children}</main>

    <footer>
      <Flex justifyContent="center">
        <a
          href="https://github.com/wmalarski"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by @me
        </a>
      </Flex>
    </footer>
  </div>
);
